export * from './CategoriasProductos/page';
export * from './Dashboard/page';
export * from './Login/page';
export * from './NotFound/page';
export * from './Nothing/page';
export * from './Roles/page';
export * from './Usuarios/page';
export * from './Proveedores/page';
export * from './Productos/page';
export * from './Laboratorios/page';
export * from './LotesProductos/page';
export * from './PrincipiosActivos/page'
export * from './Compras/page'
export * from './Clientes/page'
export * from './Ventas/page'
export * from './Movimientos/page'
export * from './Reportes/page'